# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: 'default'


steps:
# The first task is the dotnet command build, pointing to our csproj file
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
 #   projects: '*/*.csproj'
    projects: '/home/avihu/Downloads/myagent/_work/1/s/hello/hello.csproj'
    #OUTPUT   hello -> /home/avihu/Downloads/myagent/_work/1/s/hello/bin/Debug/net8.0/hello.dll
  
#- publish: $(System.DefaultWorkingDirectory)/bin/Debug/net8.0/hello.dll
- publish: '/home/avihu/Downloads/myagent/_work/1/s/hello/bin/Debug/net8.0/hello.dll'
  artifact: hello.dll  

    

- script: pwd
 