trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  name: 'default'


steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '/home/avihu/studies/dotnet/hello/hello.csproj'
- script: cd hello && ls
  displayName: 'ls'
   # projects: '/home/avihu/Downloads/myagent/_work/1/s/hello/hello.csproj'
    #OUTPUT   hello -> /home/avihu/Downloads/myagent/_work/1/s/hello/bin/Debug/net8.0/hello.dll
  
#- publish: $(System.DefaultWorkingDirectory)/bin/Debug/net8.0/hello.dll
#- publish: '/home/avihu/Downloads/myagent/_work/1/s/hello/bin/Debug/net8.0/hello.dll'
 # artifact: hello.dll  

    

- script: pwd
 
